#!/usr/bin/env python3

from pathlib import Path
import re

import markdown
from markdown.extensions.toc import TocExtension


ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "specs" / "spec.md"
TEMPLATE_PATH = ROOT / "docs" / "spec.template.html"
OUTPUT_PATH = ROOT / "docs" / "spec.html"


def render() -> str:
    md = markdown.Markdown(
        extensions=[
            "fenced_code",
            "tables",
            "sane_lists",
            TocExtension(toc_depth="2-3"),
        ]
    )
    source = SPEC_PATH.read_text(encoding="utf-8")
    content_html = md.convert(source)
    toc_html = md.toc or '<div class="toc-empty">No section headings found.</div>'
    toc_html = re.sub(r'^<div class="toc">\s*', "", toc_html)
    toc_html = re.sub(r"\s*</div>\s*$", "", toc_html)

    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    html = template.replace("__TOC__", toc_html).replace("__CONTENT__", content_html)
    return (
        "<!-- Auto-generated by docs/render_spec.py from specs/spec.md. Do not edit docs/spec.html directly. -->\n"
        + html
    )


def main() -> None:
    OUTPUT_PATH.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
